# QAExchange 交易所配置文件

[server]
name = "QAExchange"
environment = "development"
log_level = "info"
worker_threads = 10

[http]
host = "0.0.0.0"
port = 8094
request_timeout = 30
max_request_size = 10
enable_cors = true
cors_origins = ["*"]

[websocket]
host = "0.0.0.0"
port = 8095
heartbeat_interval = 5
connection_timeout = 10
max_message_size = 1024
max_connections_per_user = 3

[storage]
enabled = true
base_path = "/home/quantaxis/qaexchange-rs/output/qaexchange/storage"

[storage.wal]
directory = "wal"
max_file_size = 256
sync_mode = "async"
sync_interval_ms = 100

[storage.memtable]
max_size_mb = 256
estimated_entry_size = 256

[storage.sstable]
directory = "sstables"
compression = "zstd"
compression_level = 3

[storage.subscriber]
batch_size = 100
batch_timeout_ms = 10
buffer_size = 10000

[matching]
orderbook_depth = 100
price_precision = 2
volume_precision = 0
min_order_volume = 1.0
max_order_volume = 1000.0
order_ttl = 0

[risk]
enabled = true
max_position_ratio = 80.0
max_leverage = 10.0
liquidation_ratio = 100.0
warning_ratio = 80.0
max_order_amount = 1000.0
max_daily_trades = 10000

[account]
default_init_cash = 10000000.0
min_balance = 0.0
commission_rate = 0.0003
margin_rate = 0.15

[[instruments]]
instrument_id = "IF2501"
name = "沪深300股指期货2501"
exchange_id = "CFFEX"
product_type = "futures"
contract_multiplier = 300.0
tick_size = 0.2
init_price = 3800.0
is_trading = true

[[instruments]]
instrument_id = "IC2501"
name = "中证500股指期货2501"
exchange_id = "CFFEX"
product_type = "futures"
contract_multiplier = 200.0
tick_size = 0.2
init_price = 5600.0
is_trading = true

[[instruments]]
instrument_id = "IH2501"
name = "上证50股指期货2501"
exchange_id = "CFFEX"
product_type = "futures"
contract_multiplier = 300.0
tick_size = 0.2
init_price = 2800.0
is_trading = true
