// This file is @generated by prost-build.
/// 日志复制请求
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AppendEntriesRequest {
    /// Leader term
    #[prost(uint64, tag = "1")]
    pub term: u64,
    /// Leader ID
    #[prost(string, tag = "2")]
    pub leader_id: ::prost::alloc::string::String,
    /// 前一条日志的序列号
    #[prost(uint64, tag = "3")]
    pub prev_log_sequence: u64,
    /// 前一条日志的 term
    #[prost(uint64, tag = "4")]
    pub prev_log_term: u64,
    /// 要复制的日志条目
    #[prost(message, repeated, tag = "5")]
    pub entries: ::prost::alloc::vec::Vec<LogEntry>,
    /// Leader 的 commit 序列号
    #[prost(uint64, tag = "6")]
    pub leader_commit: u64,
}
/// 日志复制响应
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AppendEntriesResponse {
    /// Follower term
    #[prost(uint64, tag = "1")]
    pub term: u64,
    /// 是否成功
    #[prost(bool, tag = "2")]
    pub success: bool,
    /// 当前匹配的序列号
    #[prost(uint64, tag = "3")]
    pub match_sequence: u64,
    /// 错误信息
    #[prost(string, tag = "4")]
    pub error: ::prost::alloc::string::String,
}
/// 日志条目
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LogEntry {
    /// 序列号
    #[prost(uint64, tag = "1")]
    pub sequence: u64,
    /// Term
    #[prost(uint64, tag = "2")]
    pub term: u64,
    /// WAL 记录 (rkyv 序列化后的字节)
    #[prost(bytes = "vec", tag = "3")]
    pub record_data: ::prost::alloc::vec::Vec<u8>,
    /// 时间戳 (纳秒)
    #[prost(int64, tag = "4")]
    pub timestamp: i64,
    /// 记录类型
    #[prost(enumeration = "RecordType", tag = "5")]
    pub record_type: i32,
}
/// 心跳请求
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HeartbeatRequest {
    /// Leader term
    #[prost(uint64, tag = "1")]
    pub term: u64,
    /// Leader ID
    #[prost(string, tag = "2")]
    pub leader_id: ::prost::alloc::string::String,
    /// Leader commit 序列号
    #[prost(uint64, tag = "3")]
    pub leader_commit: u64,
    /// 时间戳
    #[prost(int64, tag = "4")]
    pub timestamp: i64,
}
/// 心跳响应
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HeartbeatResponse {
    /// Follower term
    #[prost(uint64, tag = "1")]
    pub term: u64,
    /// 节点 ID
    #[prost(string, tag = "2")]
    pub node_id: ::prost::alloc::string::String,
    /// 最后日志序列号
    #[prost(uint64, tag = "3")]
    pub last_log_sequence: u64,
    /// 是否健康
    #[prost(bool, tag = "4")]
    pub healthy: bool,
    /// 节点状态
    #[prost(message, optional, tag = "5")]
    pub status: ::core::option::Option<NodeStatus>,
}
/// 节点状态
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct NodeStatus {
    /// CPU 使用率 (0-100)
    #[prost(float, tag = "1")]
    pub cpu_usage: f32,
    /// 内存使用率 (0-100)
    #[prost(float, tag = "2")]
    pub memory_usage: f32,
    /// 磁盘使用率 (0-100)
    #[prost(float, tag = "3")]
    pub disk_usage: f32,
    /// 待复制日志数量
    #[prost(uint64, tag = "4")]
    pub pending_logs: u64,
    /// 复制延迟 (毫秒)
    #[prost(uint64, tag = "5")]
    pub replication_lag_ms: u64,
}
/// 快照块 (流式传输)
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SnapshotChunk {
    /// Leader term
    #[prost(uint64, tag = "1")]
    pub term: u64,
    /// 快照包含的最后序列号
    #[prost(uint64, tag = "2")]
    pub last_included_sequence: u64,
    /// 快照包含的最后 term
    #[prost(uint64, tag = "3")]
    pub last_included_term: u64,
    /// 块索引
    #[prost(uint64, tag = "4")]
    pub chunk_index: u64,
    /// 总块数
    #[prost(uint64, tag = "5")]
    pub total_chunks: u64,
    /// 数据
    #[prost(bytes = "vec", tag = "6")]
    pub data: ::prost::alloc::vec::Vec<u8>,
    /// 是否是最后一块
    #[prost(bool, tag = "7")]
    pub is_last: bool,
}
/// 快照响应
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SnapshotResponse {
    /// Follower term
    #[prost(uint64, tag = "1")]
    pub term: u64,
    /// 是否成功
    #[prost(bool, tag = "2")]
    pub success: bool,
    /// 错误信息
    #[prost(string, tag = "3")]
    pub error: ::prost::alloc::string::String,
    /// 接收的字节数
    #[prost(uint64, tag = "4")]
    pub bytes_received: u64,
}
/// 投票请求
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct VoteRequest {
    /// Candidate term
    #[prost(uint64, tag = "1")]
    pub term: u64,
    /// Candidate ID
    #[prost(string, tag = "2")]
    pub candidate_id: ::prost::alloc::string::String,
    /// Candidate 的最后日志序列号
    #[prost(uint64, tag = "3")]
    pub last_log_sequence: u64,
    /// Candidate 的最后日志 term
    #[prost(uint64, tag = "4")]
    pub last_log_term: u64,
}
/// 投票响应
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct VoteResponse {
    /// Follower term
    #[prost(uint64, tag = "1")]
    pub term: u64,
    /// 是否投票给该 Candidate
    #[prost(bool, tag = "2")]
    pub vote_granted: bool,
    /// 节点 ID
    #[prost(string, tag = "3")]
    pub voter_id: ::prost::alloc::string::String,
}
/// 记录类型
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum RecordType {
    Unknown = 0,
    OrderInsert = 1,
    OrderCancel = 2,
    TradeExecuted = 3,
    AccountUpdate = 4,
    PositionUpdate = 5,
    TickData = 6,
    OrderbookSnapshot = 7,
    Checkpoint = 8,
}
impl RecordType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unknown => "RECORD_TYPE_UNKNOWN",
            Self::OrderInsert => "RECORD_TYPE_ORDER_INSERT",
            Self::OrderCancel => "RECORD_TYPE_ORDER_CANCEL",
            Self::TradeExecuted => "RECORD_TYPE_TRADE_EXECUTED",
            Self::AccountUpdate => "RECORD_TYPE_ACCOUNT_UPDATE",
            Self::PositionUpdate => "RECORD_TYPE_POSITION_UPDATE",
            Self::TickData => "RECORD_TYPE_TICK_DATA",
            Self::OrderbookSnapshot => "RECORD_TYPE_ORDERBOOK_SNAPSHOT",
            Self::Checkpoint => "RECORD_TYPE_CHECKPOINT",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "RECORD_TYPE_UNKNOWN" => Some(Self::Unknown),
            "RECORD_TYPE_ORDER_INSERT" => Some(Self::OrderInsert),
            "RECORD_TYPE_ORDER_CANCEL" => Some(Self::OrderCancel),
            "RECORD_TYPE_TRADE_EXECUTED" => Some(Self::TradeExecuted),
            "RECORD_TYPE_ACCOUNT_UPDATE" => Some(Self::AccountUpdate),
            "RECORD_TYPE_POSITION_UPDATE" => Some(Self::PositionUpdate),
            "RECORD_TYPE_TICK_DATA" => Some(Self::TickData),
            "RECORD_TYPE_ORDERBOOK_SNAPSHOT" => Some(Self::OrderbookSnapshot),
            "RECORD_TYPE_CHECKPOINT" => Some(Self::Checkpoint),
            _ => None,
        }
    }
}
/// Generated client implementations.
pub mod replication_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    #[derive(Debug, Clone)]
    pub struct ReplicationServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl ReplicationServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> ReplicationServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::BoxBody>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> ReplicationServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::BoxBody>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            ReplicationServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// 日志复制 (Master → Slave)
        pub async fn append_entries(
            &mut self,
            request: impl tonic::IntoRequest<super::AppendEntriesRequest>,
        ) -> std::result::Result<
            tonic::Response<super::AppendEntriesResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/qaexchange.replication.ReplicationService/AppendEntries",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "qaexchange.replication.ReplicationService",
                        "AppendEntries",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// 心跳检测
        pub async fn heartbeat(
            &mut self,
            request: impl tonic::IntoRequest<super::HeartbeatRequest>,
        ) -> std::result::Result<
            tonic::Response<super::HeartbeatResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/qaexchange.replication.ReplicationService/Heartbeat",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "qaexchange.replication.ReplicationService",
                        "Heartbeat",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// 快照传输
        pub async fn install_snapshot(
            &mut self,
            request: impl tonic::IntoStreamingRequest<Message = super::SnapshotChunk>,
        ) -> std::result::Result<
            tonic::Response<super::SnapshotResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/qaexchange.replication.ReplicationService/InstallSnapshot",
            );
            let mut req = request.into_streaming_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "qaexchange.replication.ReplicationService",
                        "InstallSnapshot",
                    ),
                );
            self.inner.client_streaming(req, path, codec).await
        }
        /// 请求投票 (选举)
        pub async fn request_vote(
            &mut self,
            request: impl tonic::IntoRequest<super::VoteRequest>,
        ) -> std::result::Result<tonic::Response<super::VoteResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/qaexchange.replication.ReplicationService/RequestVote",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "qaexchange.replication.ReplicationService",
                        "RequestVote",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// 流式日志复制 (高性能批量复制)
        pub async fn stream_append_entries(
            &mut self,
            request: impl tonic::IntoStreamingRequest<
                Message = super::AppendEntriesRequest,
            >,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::AppendEntriesResponse>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/qaexchange.replication.ReplicationService/StreamAppendEntries",
            );
            let mut req = request.into_streaming_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "qaexchange.replication.ReplicationService",
                        "StreamAppendEntries",
                    ),
                );
            self.inner.streaming(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod replication_service_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with ReplicationServiceServer.
    #[async_trait]
    pub trait ReplicationService: std::marker::Send + std::marker::Sync + 'static {
        /// 日志复制 (Master → Slave)
        async fn append_entries(
            &self,
            request: tonic::Request<super::AppendEntriesRequest>,
        ) -> std::result::Result<
            tonic::Response<super::AppendEntriesResponse>,
            tonic::Status,
        >;
        /// 心跳检测
        async fn heartbeat(
            &self,
            request: tonic::Request<super::HeartbeatRequest>,
        ) -> std::result::Result<
            tonic::Response<super::HeartbeatResponse>,
            tonic::Status,
        >;
        /// 快照传输
        async fn install_snapshot(
            &self,
            request: tonic::Request<tonic::Streaming<super::SnapshotChunk>>,
        ) -> std::result::Result<
            tonic::Response<super::SnapshotResponse>,
            tonic::Status,
        >;
        /// 请求投票 (选举)
        async fn request_vote(
            &self,
            request: tonic::Request<super::VoteRequest>,
        ) -> std::result::Result<tonic::Response<super::VoteResponse>, tonic::Status>;
        /// Server streaming response type for the StreamAppendEntries method.
        type StreamAppendEntriesStream: tonic::codegen::tokio_stream::Stream<
                Item = std::result::Result<super::AppendEntriesResponse, tonic::Status>,
            >
            + std::marker::Send
            + 'static;
        /// 流式日志复制 (高性能批量复制)
        async fn stream_append_entries(
            &self,
            request: tonic::Request<tonic::Streaming<super::AppendEntriesRequest>>,
        ) -> std::result::Result<
            tonic::Response<Self::StreamAppendEntriesStream>,
            tonic::Status,
        >;
    }
    #[derive(Debug)]
    pub struct ReplicationServiceServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> ReplicationServiceServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for ReplicationServiceServer<T>
    where
        T: ReplicationService,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::BoxBody>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/qaexchange.replication.ReplicationService/AppendEntries" => {
                    #[allow(non_camel_case_types)]
                    struct AppendEntriesSvc<T: ReplicationService>(pub Arc<T>);
                    impl<
                        T: ReplicationService,
                    > tonic::server::UnaryService<super::AppendEntriesRequest>
                    for AppendEntriesSvc<T> {
                        type Response = super::AppendEntriesResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::AppendEntriesRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as ReplicationService>::append_entries(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = AppendEntriesSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/qaexchange.replication.ReplicationService/Heartbeat" => {
                    #[allow(non_camel_case_types)]
                    struct HeartbeatSvc<T: ReplicationService>(pub Arc<T>);
                    impl<
                        T: ReplicationService,
                    > tonic::server::UnaryService<super::HeartbeatRequest>
                    for HeartbeatSvc<T> {
                        type Response = super::HeartbeatResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::HeartbeatRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as ReplicationService>::heartbeat(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = HeartbeatSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/qaexchange.replication.ReplicationService/InstallSnapshot" => {
                    #[allow(non_camel_case_types)]
                    struct InstallSnapshotSvc<T: ReplicationService>(pub Arc<T>);
                    impl<
                        T: ReplicationService,
                    > tonic::server::ClientStreamingService<super::SnapshotChunk>
                    for InstallSnapshotSvc<T> {
                        type Response = super::SnapshotResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<
                                tonic::Streaming<super::SnapshotChunk>,
                            >,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as ReplicationService>::install_snapshot(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = InstallSnapshotSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.client_streaming(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/qaexchange.replication.ReplicationService/RequestVote" => {
                    #[allow(non_camel_case_types)]
                    struct RequestVoteSvc<T: ReplicationService>(pub Arc<T>);
                    impl<
                        T: ReplicationService,
                    > tonic::server::UnaryService<super::VoteRequest>
                    for RequestVoteSvc<T> {
                        type Response = super::VoteResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::VoteRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as ReplicationService>::request_vote(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = RequestVoteSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/qaexchange.replication.ReplicationService/StreamAppendEntries" => {
                    #[allow(non_camel_case_types)]
                    struct StreamAppendEntriesSvc<T: ReplicationService>(pub Arc<T>);
                    impl<
                        T: ReplicationService,
                    > tonic::server::StreamingService<super::AppendEntriesRequest>
                    for StreamAppendEntriesSvc<T> {
                        type Response = super::AppendEntriesResponse;
                        type ResponseStream = T::StreamAppendEntriesStream;
                        type Future = BoxFuture<
                            tonic::Response<Self::ResponseStream>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<
                                tonic::Streaming<super::AppendEntriesRequest>,
                            >,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as ReplicationService>::stream_append_entries(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = StreamAppendEntriesSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.streaming(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(empty_body());
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for ReplicationServiceServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "qaexchange.replication.ReplicationService";
    impl<T> tonic::server::NamedService for ReplicationServiceServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
